# K Fold cross validation

* split the data into *K* folds/samples
    * use K-1 samples/folds for training the model and the remaining one for testing
        - do this K times i.e each of the K samples used as a test sample
        - each time, calculate the score/model performance index
 * compare performance of classifiers/models  
 * note that we can also use the K Fold classifier to determine the appropriate parameter/tuning parameter within a classifier
     - for instance in Random forest, for n_estimators

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, test_size=0.3)

## Logistic classifier/model

In [62]:
lr = LogisticRegression(max_iter=5000)
lr.fit(X_train, Y_train)
lr.score(X_test, Y_test)

0.9574074074074074

## Support vector machines/SVM

In [63]:
svm = SVC()
svm.fit(X_train, Y_train)
svm.score(X_test, Y_test)

0.9814814814814815

## Random forest

In [64]:
rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

0.9648148148148148

## K-Fold classification

For more info, check the video below:

In [65]:
%%HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/gJo0uNL-5Qw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Setting up the K-Fold validation manually

In [66]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [67]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [68]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [69]:
get_score(LogisticRegression(max_iter=5000), X_train, X_test, Y_train, Y_test)

0.9574074074074074

In [70]:
get_score(SVC(), X_train, X_test, Y_train, Y_test)

0.9814814814814815

In [71]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [72]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], \
    digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(max_iter=5000), X_train, X_test, Y_train, Y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, Y_train, Y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, Y_train, Y_test))
 
    
    

In [73]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [74]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [75]:
scores_rf

[0.9432387312186978, 0.9499165275459098, 0.9198664440734557]

## K Fold validation from cross_validation package

In [76]:
from sklearn.model_selection import cross_val_score

In [77]:
cross_val_score(LogisticRegression(max_iter=5000), digits.data, digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])

In [78]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [79]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.93333333, 0.9       , 0.96657382, 0.97214485, 0.93036212])