In [1]:
%%HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/Fuw0wv3X-0o?si=6ikH1Kk920Sdq6mK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [5]:
reviews = ['nice food',
          'amazing restaurant',
          'too good',
          'just loved it',
          'will go again',
          'horrible food',
          'never go there',
          'poor service',
          'poor quality',
          'needs improvement'
         ]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing restuarant", 30)

[5, 21]

In [7]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[7, 13],
 [5, 1],
 [15, 11],
 [7, 3, 14],
 [2, 2, 12],
 [14, 13],
 [7, 2, 24],
 [21, 21],
 [21, 17],
 [18, 6]]

In [9]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[ 7, 13,  0],
       [ 5,  1,  0],
       [15, 11,  0],
       [ 7,  3, 14],
       [ 2,  2, 12],
       [14, 13,  0],
       [ 7,  2, 24],
       [21, 21,  0],
       [21, 17,  0],
       [18,  6,  0]])

In [15]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, 
                   name = 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [16]:
X = padded_reviews
y = sentiment

In [17]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.fit(X, y, epochs=50, verbose=0)

In [19]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 197ms/step - loss: 0.6309 - accuracy: 1.0000


1.0

In [23]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [24]:
weights[11]

array([-0.09687883,  0.0624086 ,  0.01049071, -0.00085465], dtype=float32)

In [25]:
weights[3]

array([-0.07308988,  0.04761536,  0.09064188, -0.03992421], dtype=float32)